# Upgrade to Yarn 4.14+ which adds the approvedGitRepositories setting.
nodeLinker: node-modules
## Don't run lifecycle scripts by default. You can still
## allow them on a per-package basis with @lavamoat/allow-scripts
enableScripts: false
## Allowlist of git dependencies. Empty to block all git deps.
approvedGitRepositories: []
## Avoid installing packages published in last 3 days
npmMinimalAgeGate: 4320 # 3 days (in minutes)
## Override the minimal age gate, allowing certain packages
## to be installed regardless of their publish age.
#npmPreapprovedPackages:
#  - '@yournamespace/*'
