name: Main CI/CD

on:
  push:
    branches:
      - main

jobs:
  verify-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
        env:
          NPM_CLIENT: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run linters
        run: yarn lint
      - name: 🧪 Run low-level tests
        run: sleep 5

  build:
    runs-on: ubuntu-latest
    needs: [verify-code]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
        env:
          NPM_CLIENT: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      pages: write 
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Wait for deployment to be ready
        run: sleep 30

  acceptance-tests:
    needs: [deploy]
    uses: ./.github/workflows/playwright-e2e-tests.yaml
    with:
      sut-base-url: 'https://jvbriones.github.io/'
